name: Build and Deploy CoinCash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 20.x

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create .env.local file
      run: |
        cat <<EOT > .env.local
        # Web3 Configuration
        NEXT_PUBLIC_ALCHEMY_API_KEY=your_alchemy_api_key_here
        NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=your_walletconnect_project_id
        
        # Next.js Configuration
        NEXT_PUBLIC_SITE_URL=https://your-production-url.com
        NEXTAUTH_URL=http://localhost:3000
        NEXTAUTH_SECRET=$(openssl rand -base64 32)
        
        # API Keys (Add your production API keys here)
        # NEXT_PUBLIC_INFURA_ID=your_infura_id
        # NEXT_PUBLIC_ETHERSCAN_API_KEY=your_etherscan_api_key
        
        # Feature Flags
        # NEXT_PUBLIC_ENABLE_TESTNETS=true
        
        # Optional: Database configuration if needed
        # DATABASE_URL=your_database_url
        EOT

    - name: Run Linter
      run: npm run lint

    - name: Run Tests
      run: npm test
      if: success()

    - name: Build Application
      run: npm run build
      env:
        # Add any build-time environment variables here
        NODE_ENV: production

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          .next
          public
          package.json
          next.config.js
          next.config.mjs

  deploy:
    name: Deploy
    needs: build
    if: github.ref == 'refs/heads/main'  # Only run on main branch
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install production dependencies
        run: npm ci --production

      # Add your deployment steps here
      # Example for Vercel:
      # - name: Install Vercel CLI
      #   run: npm install -g vercel
      # 
      # - name: Deploy to Vercel
      #   run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
      #   env:
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
