---
# Ansible playbook to install Node.js on Ubuntu
# Usage: ansible-playbook -i inventory.ini install_nodejs.yml

- name: Install Node.js on Ubuntu
  hosts: all
  become: yes
  vars:
    node_version: "20.x"  # Specify the Node.js version you want to install
    npm_version: "latest"  # Specify npm version or 'latest'

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600  # 1 hour

    - name: Install required system packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Add NodeSource repository key
      ansible.builtin.shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
      args:
        creates: /etc/apt/keyrings/nodesource.gpg

    - name: Add NodeSource repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }}.x nodistro main"
        state: present
        filename: nodesource
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
        state: present

    - name: Install specific npm version if not 'latest'
      when: npm_version != 'latest'
      npm:
        name: npm
        global: yes
        version: "{{ npm_version }}"

    - name: Install Yarn (optional)
      npm:
        name: yarn
        global: yes
      when: install_yarn | default(false)  # Set to true in extra_vars if needed

    - name: Verify Node.js and npm installation
      command: node --version
      register: node_version_check
      changed_when: false

    - name: Show Node.js version
      debug:
        msg: "Node.js {{ node_version_check.stdout }} installed successfully"

    - name: Verify npm installation
      command: npm --version
      register: npm_version_check
      changed_when: false

    - name: Show npm version
      debug:
        msg: "npm {{ npm_version_check.stdout }} installed successfully"
